<?php

/**
 *  @var \Magezil\BoughtTogether\Block\Product\View $block
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\ActionInterface;
use Magento\Wishlist\Helper\Data as WishlistData;
use Magento\Catalog\Helper\Product\Compare;

$boughtTogetherConfigs = $this->getBoughtTogetherConfig();
$title = $block->getBoughtTogetherTitle();

$image = 'category_page_list';
$templateType = ReviewRendererInterface::SHORT_VIEW;
?>

<?php if ($block->isShowBlock()) : ?>
    <section class="block block-bought-together">
        <header class="block-title title">
            <strong id="block-bought-together-heading" role="heading" aria-level="2">
                <?= $title ?>
            </strong>
        </header>

        <div class="block-actions">
            <?= __('Check items to add to the cart or') ?>

            <button type="button" class="action select" id="select_all_bought_together" data-role="select-all-bought-together">
                <?= __('select all') ?>
            </button>

            <form data-role="tocart-form" action="<?= $block->getAddProductsSelectedInCartUrl() ?>" method="POST">
                <button type="submit" class="action to cart primary" id="add_all_bought_together">
                    <?= __('All selected in cart') ?>
                </button>

                <input id="product_ids" name="productIds" />
            </form>
        </div>

        <article class="block-content content block-content-bought-together" aria-labelledby="block-bought-together-heading">
            <div class="products wrapper grid products-grid products-bought-together">
                <ol class="products list items product-items">
                    <?php foreach ($block->getLoadedProductCollection() as $_item) : ?>
                        <li class="card-list item product product-item">
                            <div class="product-item-info">
                                <?= '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>

                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?= $_item->getName() ?>" href="<?= $block->getProductUrl($_item) ?>">
                                            <?= $_item->getName() ?>
                                        </a>
                                    </strong>

                                    <!-- Product Price -->
                                    <?= $block->getProductPrice($_item) ?>

                                    <?php if ($templateType) : ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if (!$_item->getRequiredOptions()) : ?>
                                        <div class="field choice bought-together">
                                            <input type="checkbox" class="checkbox-bought-together" id="bought-together-checkbox_<?= $_item->getId() ?>" name="similar_products[]" value="<?= $_item->getId() ?>" />
                                            <label class="label" for="bought-together-checkbox_<?= $_item->getId() ?>">
                                                <span>
                                                    <?= __('Add to Cart') ?>
                                                </span>
                                            </label>
                                        </div>
                                    <?php endif; ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $_item->getSku() ?>" action="<?= $postParams['action'] ?>" method="post">
                                                        <?php if ($boughtTogetherConfigs->isShowQtyProducts()) : ?>
                                                            <div class="field qty">
                                                                <label class="label" for="qty_<?= $_item->getId() ?>">
                                                                    <span>
                                                                        <?= __('Qty') ?>
                                                                    </span>
                                                                </label>
                                                                <div class="control">
                                                                    <input type="number" name="qty" id="qty_<?= $_item->getId() ?>" min="1" value="1" title="<?= __('Qty') ?>" class="input-text qty" data-product-qty="<?= $_item->getProductId() ?>" />
                                                                </div>
                                                            </div>
                                                        <?php endif; ?>
                                                        <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= ActionInterface::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit" title="<?= __('Add to Cart') ?>" class="action tocart primary add-to-cart">
                                                            <span>
                                                                <?= __('Add to Cart') ?>
                                                            </span>
                                                        </button>
                                                    </form>
                                                <?php else : ?>
                                                    <?php if ($_item->isAvailable()) : ?>
                                                        <div class="stock available">
                                                            <span>
                                                                <?= __('In stock') ?>
                                                            </span>
                                                        </div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable">
                                                            <span>
                                                                <?= __('Out of stock') ?>
                                                            </span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <div class="product-item-actions">
                                            <div data-role="add-to-links" class="actions-secondary" style="position: relative;">
                                                <!-- Add Product to Wishlist  -->
                                                <?php if ($this->helper(WishlistData::class)->isAllow()) : ?>
                                                    <?php if ($boughtTogetherConfigs->isShowWishlist()) : ?>
                                                        <a href="#" data-post='<?= $this->helper(WishlistData::class)->getAddParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= __('Add to Wish List') ?>">
                                                            <span><?= __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>

                                                <!-- Add Product to Comparison List -->
                                                <?php if ($boughtTogetherConfigs->isShowCompare()) : ?>
                                                    <?php $compareHelper = $this->helper(Compare::class); ?>
                                                    <a href="#" class="action tocompare" title="<?= __('Add to Compare List') ?>" aria-label="<?= __('Add to Compare List') ?>" data-post='<?= $compareHelper->getPostDataParams($_item); ?>' role="button">
                                                        <span><?= __('Add to Compare List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </article>
    </section>
    <script type="text/x-magento-init">
        {
            "*":
            {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wishlist": {
                            "component": "Magento_Wishlist/js/view/wishlist"
                        }
                    }
                }
            }
        }
    </script>
    <script type="text/javascript">
        require([
            'jquery'
        ], function($) {

            // Select all products
            let boughtTogetherProducts = $('.block-bought-together .block-content-bought-together').find('.product-item'),
                boughtTogetherSelected = false,
                productObject = {
                    products: {}
                };

            $('body').on('click', '#select_all_bought_together', function() {
                if (boughtTogetherSelected) {
                    $.each(boughtTogetherProducts, function(index, item) {
                        $(item).find('.checkbox-bought-together').prop('checked', false);
                    });

                    $('#product_ids').val('{}');
                    boughtTogetherSelected = false;
                } else {
                    $.each(boughtTogetherProducts, function(index, item) {
                        let productId = $(item).find('[data-product-id]').data('product-id'),
                            productQty = $(item).find('[data-product-qty]').val(),
                            currentProduct = [];

                        $(item).find('.checkbox-bought-together').prop('checked', true);

                        currentProduct[index] = {
                            'productId': productId,
                            'qty': productQty
                        };

                        Object.assign(productObject.products, currentProduct)
                    });

                    $('#product_ids').val(JSON.stringify(productObject));
                    boughtTogetherSelected = true;
                }
            });

            $('body').on('click', '.checkbox-bought-together', function(event) {
                let boughtTogetherProductsSelecteds = JSON.parse($('#product_ids').val()),
                    productId = (event.target).val();

                    console.log(productId)

                $.each(boughtTogetherProductsSelecteds.products, function(index, product) {
                    console.log(product.productId)
                    if (product.productId == productId) {
                        delete boughtTogetherProductsSelecteds.products[index]
                    }
                });
            });
        });
    </script>
<?php endif; ?>

<!-- "Magezil_BoughtTogether/js/carouselBoughtTogether": {}, -->