<?php

/** @var \CustomModules\BoughtTogether\Block\Product\Items $block */

use CustomModules\BoughtTogether\Helper\Data;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;
use Magento\Wishlist\Helper\Data as WishlistData;
use Magento\Catalog\Helper\Product\Compare;

$_helper = $this->helper(Data::class);

$type = 'bought-together';
$image = 'category_page_list';
$templateType = ReviewRendererInterface::SHORT_VIEW;

if ($_helper->hasBoughtTogetherTitle()) {
    $title = $_helper->getBoughtTogetherTitle();
} else {
    $title = __('Frequently Bought Together:');
}
$items = $block->getFrequentlyBoughtTogether();
?>

<?php if ($block->isShowBlock()) : ?>
    <div class="block <?= $type ?>">

        <div class="block-title title">
            <strong id="block-<?= $type ?>-heading" role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
        </div>

        <div class="block-actions">
            <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
            <button type="button" class="action select" id="select_all_bought_together" data-role="select-all-bought-together"><span id="button_select_all_bought_together"><?= $block->escapeHtml(__('select all')) ?></span></button>
            <form data-role="tocart-form" action="<?= $block->getUrl('boughtTogether/cart/addto') ?>" method="post">
                <button type="submit" class="action to cart primary" id="add_all_bought_together"><?= __('All selected in cart') ?></button>
                <input id="product_ids" name="productIds" type="hidden" />
            </form>
        </div>

        <div class="block-content content block-content-bought-together" aria-labelledby="block-<?= $type ?>-heading">
            <div class="products wrapper grid products-grid products-<?= $type ?>">
                <ol class="products list items product-items">
                    <?php foreach ($items as $_item) : ?>
                        <li class="card-list item product product-item">
                            <div class="product-item-info">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>

                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtmlAttr($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <!-- Product Price -->
                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                    <?php if ($templateType) : ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if (!$_item->getRequiredOptions()) : ?>
                                        <div class="field choice bought-together">
                                            <input type="checkbox" class="checkbox bought-together" id="bought-together-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>" name="similar_products[]" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                            <label class="label" for="bought-together-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></label>
                                        </div>
                                    <?php endif; ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                        <?php if ($_helper->isShowQtyProducts()) : ?>
                                                            <div class="field qty">
                                                                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                                                                <div class="control">
                                                                    <input type="number" name="qty" id="qty" min="0" value="<?= $block->getProductDefaultQty() * 1 ?>" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty" data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                                                                </div>
                                                            </div>
                                                        <?php endif; ?>
                                                        <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary add-to-cart">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else : ?>
                                                    <?php if ($_item->isAvailable()) : ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <div class="product-item-actions">
                                            <div data-role="add-to-links" class="actions-secondary" style="position: relative;">
                                                <?php if ($this->helper(WishlistData::class)->isAllow()) : ?>
                                                    <?php if ($_helper->isShowWishlist()) : ?>
                                                        <a href="#" data-post='<?= $this->helper(WishlistData::class)->getAddParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <?php if ($_helper->isShowCompare()) : ?>
                                                    <a href="#" data-post="<?= $this->helper(Compare::class)->getAddUrl($_item) ?>" class="action tocompare" title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>" data-role="add-to-links">
                                                        <span><?= __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*":
            {
                "CustomModules_BoughtTogether/js/carouselBoughtTogether": {},
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wishlist": {
                            "component": "Magento_Wishlist/js/view/wishlist"
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>