<?php

/** @var \CustomModules\BoughtTogether\Block\Product\Items $block */

use Magento\Catalog\Block\Product\ListProduct;

$_helper = $this->helper(\CustomModules\BoughtTogether\Helper\Data::class);
?>

<?php if ($_helper->isEnabled()) : ?>
    <h1><?= $block->getBlockTitle() ?></h1>
    <?= $block->getLayout()
        ->createBlock(ListProduct::class)
        ->setCollection($block->getLoadedProductCollection())
        ->setTemplate('Magento_Catalog::product/list.phtml')
        ->toHtml() ?>
<?php endif; ?>